<?php
/**
 * @author    Agence Dn'D <contact@dnd.fr>
 * @copyright 2018 Agence Dn'D
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      https://www.pimgento.com/
 */

/**
 * @var string $runUrl
 * @var \Pimgento\Api\Block\Adminhtml\Import $block
 */
?>
<div class="pimgento-uploader">
    <div class="pimgento-step">
        <h2><?php echo __('Select import type:') ?></h2>
        <div class="pimgento-types">
            <?php $collection = $block->getCollection() ?>
            <?php /** @var mixed $import */ ?>
            <?php foreach ($collection as $import): ?>
                <?php if ($block->isAllowed($import->getCode())): ?>
                    <div class="import-type" onclick="Pimgento.type('<?php echo $import->getCode() ?>', this)">
                        <?php echo $import->getName() ?>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="pimgento-step step-last">
        <button type="button" class="primary" onclick="Pimgento.run()">
            <span class="ui-button-text">
                <span><?php echo __('Import') ?></span>
            </span>
        </button>
    </div>
</div>

<ul class="pimgento-console">
    <li class="selected"><?php echo __('Waiting for import...') ?></li>
</ul>

<script>
    require(
        ["Pimgento_Api/js/pimgento"],
        function (pimgento) {
            pimgento.init('<?php echo $runUrl; ?>', '.pimgento-console');
            window.Pimgento = pimgento;
        }
    );
</script>
